### ISSUE TITLE
How to add custom response properties?

### ISSUE THREAD

**Issue by ChaosPower** [ellipsesynergie/api-response#19]
Hi,

Would like to know how to add custom top level properties? Did not see at the docs how to do it.

**Comment by maximebeaudoin** [comment]
@ChaosPower By default, you can't, because i use the  [DataArraySerializer](https://github.com/thephpleague/fractal/blob/master/src/Serializer/DataArraySerializer.php).

If you want to change the output format, you have to change the serializer. To do that, you have to create your own service provider. You can see the [service provider](https://github.com/ellipsesynergie/api-response/blob/master/src/Laravel/ResponseServiceProvider.php#L39) of this package  for more details.

**Comment by ChaosPower** [comment]
@maximebeaudoin thanks! That hint will do. I'm trying to follow  [google's JSON style guide](https://google.github.io/styleguide/jsoncstyleguide.xml).
