### ISSUE TITLE
Lumen5.4 not parse include

### ISSUE THREAD

**Issue by HuNanZai** [ellipsesynergie/api-response#37]
### Steps to reproduce
1. using api-response in lumen 5.4
2. 
3.

### Expected behaviour
the get param:include won't be analyzed

seems that when the code runs into the `LumenServiceProvider`, `Http/Request` class still not init yet.
it'll init in the code below where in the `$app->run` method.(actual code is the traits `Concerns/RoutesRequest.php` method `parseIncomingRequest`)

so i fixed this by reparsing in my controller.

**Comment by maximebeaudoin** [comment]
@HuNanZai Thank you for your report. The problem is related to the change in Lumen boostraping, related to this https://laravel-news.com/request-object-changes-in-lumen-5-4.

Related to this commit : https://github.com/laravel/lumen-framework/commit/2ce2eaaaebd315eefcba312de1e568a1b39fcaa5

Issue reported in Lumen : https://github.com/laravel/lumen-framework/issues/565

For now, you can probably create a middleware and call the parseInclude to the manager like this 

```
app(EllipseSynergie\ApiResponse\Contracts\Response::class)
    ->getManager()
    ->parseIncludes(explode(',', app(Illuminate\Http\Request::class)->get('include')));
```

You can also provide a PR to fix the problem directly in this package.

**Comment by maximebeaudoin** [comment]
We have created a middleware to fix this issue, see https://github.com/ellipsesynergie/api-response/commit/25b8d2de92056386ad163d2d26b59c789caac7a7
