### ISSUE TITLE
Tag stable

### ISSUE THREAD

**Issue by etiennemarais** [ellipsesynergie/api-response#9]
Hi,

Please can you tag a stable version of the LengthAwarePaginator fix? I can't run my production app in stable because there is no tag for 0.9.*

**Comment by yajra** [comment]
+1.. having the same issue but I guess the problem was `fractal` have not released the fix for this. Maybe we should just use `thephpleague/fractal:dev-master` for Laravel 5 version?

**Comment by maximebeaudoin** [comment]
I can't tag stable version right know because i currently use the dev version of `league/fractal` to work with Laravel 5. Until the next release of `league/fractal`, the version 0.9.* is NOT considered stable.

I know it's cause some trouble right now but you can follow this issue https://github.com/thephpleague/fractal/issues/150

**Comment by etiennemarais** [comment]
Thanks for the reply. I completely understand. I think we should leave this open until they tagged? Do you agree?

**Comment by maximebeaudoin** [comment]
Yep, i will.

**Comment by maximebeaudoin** [comment]
https://github.com/ellipsesynergie/api-response/releases/tag/0.9.0
